import { Food } from "./app/shared/models/Food";
import { Tag } from "./app/shared/models/Tag";
/*
export const sample: Food[] = [
  {
    id:'1',
    name:'Pierogi',
    price:12,
    tags:['dinner','cheap','vegetarian'],
    favourite:false,
    stars:4,
    imageUrl:'assets/1.jpeg',
    origins:"Poland",
    cookTime:"25",
    inStock: 15,
    ingredients:['flour','oil','cottage cheese','onion','potatoes','butter','pepper','salt'],
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula velit sit amet elit dictum, quis porttitor nibh efficitur. Donec ultricies vulputate pretium. Aenean in orci a nisi dignissim semper. Nullam vel sagittis sem. Nam posuere nec quam sed semper. Integer vulputate eget lacus vel dignissim. Integer in mauris in.",
    gallery:['assets/gallery/1_1.jpg','assets/gallery/1_2.jpg','assets/gallery/1_3.jpg'],
    deleted:false,
  },
  {
    id:'2',
    name:'Pizza',
    price:34,
    tags:['dinner','fast-food','vegetarian'],
    favourite:false,
    stars:3,
    imageUrl:'assets/2.jpg',
    origins:"Italy",
    cookTime:"25",
    inStock: 5,
    ingredients:['flour','tomatoes','garlic','vinegar','salt','sugar','olive oil','mozzarella cheese'],
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula velit sit amet elit dictum, quis porttitor nibh efficitur. Donec ultricies vulputate pretium. Aenean in orci a nisi dignissim semper. Nullam vel sagittis sem. Nam posuere nec quam sed semper. Integer vulputate eget lacus vel dignissim. Integer in mauris in.",
    gallery:['assets/gallery/2_1.jpg','assets/gallery/2_2.jpg','assets/gallery/2_3.jpg','assets/gallery/2_4.jpg'],
    deleted:false,
  },
  {
    id:'3',
    name:'Beetroot soup',
    price:24,
    tags:['soup','spicy'],
    favourite:false,
    stars:5,
    imageUrl:'assets/3.jpg',
    origins:"Poland",
    cookTime:"15",
    inStock: 18,
    ingredients:['beetroot','carrot','parsley','leek','beet sourdough','mushrooms'],
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula velit sit amet elit dictum, quis porttitor nibh efficitur. Donec ultricies vulputate pretium. Aenean in orci a nisi dignissim semper. Nullam vel sagittis sem. Nam posuere nec quam sed semper. Integer vulputate eget lacus vel dignissim. Integer in mauris in.",
    gallery:['assets/gallery/3_1.jpg','assets/gallery/3_2.jpg','assets/gallery/3_3.jpg'],
    deleted:false,
  },
  {
    id:'4',
    name:'Burger',
    price:35,
    tags:['dinner','fast-food'],
    favourite:true,
    stars:4,
    imageUrl:'assets/4.jpg',
    origins:"International",
    cookTime:"45",
    inStock: 7,
    ingredients:['beef','onion','eggs','salt','pepper','bread','tomatoes','mozzarella cheese','pickles','arugula','lettuce'],
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula velit sit amet elit dictum, quis porttitor nibh efficitur. Donec ultricies vulputate pretium. Aenean in orci a nisi dignissim semper. Nullam vel sagittis sem. Nam posuere nec quam sed semper. Integer vulputate eget lacus vel dignissim. Integer in mauris in.",
    gallery:['assets/gallery/4_1.jpg','assets/gallery/4_2.jpg','assets/gallery/4_3.jpg','assets/gallery/4_4.jpg'],
    deleted:false,
  },
  {
    id:'5',
    name:'Chicken Tikka Masala',
    price:32,
    tags:['dinner','lunch'],
    favourite:false,
    stars:2,
    imageUrl:'assets/5.jpg',
    origins:"India",
    cookTime:"25",
    inStock: 15,
    ingredients:['chicken thighs','yogurt','garlic','ginger','garam masala','turmeric','cumin','chili','butter','tomato puree'],
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula velit sit amet elit dictum, quis porttitor nibh efficitur. Donec ultricies vulputate pretium. Aenean in orci a nisi dignissim semper. Nullam vel sagittis sem. Nam posuere nec quam sed semper. Integer vulputate eget lacus vel dignissim. Integer in mauris in.",
    gallery:['assets/gallery/5_1.jpg','assets/gallery/5_2.jpg','assets/gallery/5_3.jpg'],
    deleted:false,
  },
  {
    id:'6',
    name:'Sushi',
    price:52,
    tags:['dinner','supper','fish'],
    favourite:true,
    stars:5,
    imageUrl:'assets/6.jpg',
    origins:"Japan",
    cookTime:"35",
    inStock: 11,
    ingredients:['nori','rice','carrot','cucamber','avocado','tuna','salmon','wasabi'],
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula velit sit amet elit dictum, quis porttitor nibh efficitur. Donec ultricies vulputate pretium. Aenean in orci a nisi dignissim semper. Nullam vel sagittis sem. Nam posuere nec quam sed semper. Integer vulputate eget lacus vel dignissim. Integer in mauris in.",
    gallery:['assets/gallery/6_1.jpg','assets/gallery/6_2.jpg','assets/gallery/6_3.jpg'],
    deleted:false,
  },
  {
    id:'7',
    name:'Burrito',
    price:35,
    tags:['dinner','spicy'],
    favourite:false,
    stars:4,
    imageUrl:'assets/7.jpg',
    origins:"Mexico",
    cookTime:"20",
    inStock: 30,
    ingredients:['tortilla','cheese','onion','rice','tomatoes','beef','chili','red bean'],
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula velit sit amet elit dictum, quis porttitor nibh efficitur. Donec ultricies vulputate pretium. Aenean in orci a nisi dignissim semper. Nullam vel sagittis sem. Nam posuere nec quam sed semper. Integer vulputate eget lacus vel dignissim. Integer in mauris in.",
    gallery:['assets/gallery/7_1.jpg','assets/gallery/7_2.jpg','assets/gallery/7_3.jpg'],
    deleted:false,
  },
  {
    id:'8',
    name:'Salmon sandwitch',
    price:18,
    tags:['breakfast','lunch','fish'],
    favourite:true,
    stars:5,
    imageUrl:'assets/8.jpg',
    origins:"International",
    cookTime:"15",
    inStock: 8,
    ingredients:['salmon','bread','lettuce','cheese'],
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula velit sit amet elit dictum, quis porttitor nibh efficitur. Donec ultricies vulputate pretium. Aenean in orci a nisi dignissim semper. Nullam vel sagittis sem. Nam posuere nec quam sed semper. Integer vulputate eget lacus vel dignissim. Integer in mauris in.",
    gallery:['assets/gallery/8_1.jpg','assets/gallery/8_2.jpg','assets/gallery/8_3.jpg'],
    deleted:false,
  },
  {
    id:'9',
    name:'Tofu Stir Fry',
    price:15,
    tags:['cheap','vegan','spicy'],
    favourite:false,
    stars:3,
    imageUrl:'assets/9.jpg',
    origins:"Thai",
    cookTime:"25",
    inStock: 15,
    ingredients:['tofu','oil','soy sauce','garlic','onion','ginger','chili'],
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula velit sit amet elit dictum, quis porttitor nibh efficitur. Donec ultricies vulputate pretium. Aenean in orci a nisi dignissim semper. Nullam vel sagittis sem. Nam posuere nec quam sed semper. Integer vulputate eget lacus vel dignissim. Integer in mauris in.",
    gallery:['assets/gallery/9_1.jpg','assets/gallery/9_2.jpg','assets/gallery/9_3.jpg'],
    deleted:false,
  },
  {
    id:'10',
    name:'Fish and chips',
    price:25,
    tags:['dinner','fish'],
    favourite:false,
    stars:5,
    imageUrl:'assets/10.jpeg',
    origins:"England",
    cookTime:"35",
    inStock: 15,
    ingredients:['cod','flour','beer','lemon','eggs','potatoes'],
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula velit sit amet elit dictum, quis porttitor nibh efficitur. Donec ultricies vulputate pretium. Aenean in orci a nisi dignissim semper. Nullam vel sagittis sem. Nam posuere nec quam sed semper. Integer vulputate eget lacus vel dignissim. Integer in mauris in.",
    gallery:['assets/gallery/10_1.jpg','assets/gallery/10_2.jpg','assets/gallery/10_3.jpg'],
    deleted:false,
  },
  {
    id:'11',
    name:'Chili con carne',
    price:25,
    tags:['dinner','spicy','vegetarian'],
    favourite:true,
    stars:5,
    imageUrl:'assets/11.jpeg',
    origins:"Mexico",
    cookTime:"35",
    inStock: 12,
    ingredients:['veggie mince','red beans','bell peppers', 'carrots', 'celery','tomatoes','chili'],
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula velit sit amet elit dictum, quis porttitor nibh efficitur. Donec ultricies vulputate pretium. Aenean in orci a nisi dignissim semper. Nullam vel sagittis sem. Nam posuere nec quam sed semper. Integer vulputate eget lacus vel dignissim. Integer in mauris in.",
    gallery:['assets/gallery/11_1.jpg','assets/gallery/11_2.jpg','assets/gallery/11_3.jpg'],
    deleted:false,
  },
  {
    id:'12',
    name:'Chicken korma',
    price:22,
    tags:['dinner'],
    favourite:false,
    stars:5,
    imageUrl:'assets/12.jpg',
    origins:"India",
    cookTime:"35",
    inStock: 15,
    ingredients:['chicken','butter','onion','ginger','garlic','almonds'],
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vehicula velit sit amet elit dictum, quis porttitor nibh efficitur. Donec ultricies vulputate pretium. Aenean in orci a nisi dignissim semper. Nullam vel sagittis sem. Nam posuere nec quam sed semper. Integer vulputate eget lacus vel dignissim. Integer in mauris in.",
    gallery:['assets/gallery/12_1.jpg','assets/gallery/12_2.jpg','assets/gallery/12_3.jpg'],
    deleted:false,
  },
]

export const sample_tags:Tag[] = [
  {name:'dinner', count:9},
  {name:'cheap', count:2},
  {name:'vegetarian',count:3},
  {name:'fast-food',count:2},
  {name:'soup',count:1},
  {name:'spicy',count:4},
  {name:'lunch',count:2},
  {name:'supper',count:1},
  {name:'fish',count:3},
  {name:'breakfast',count:1},
  {name:'vegan',count:1},
]*/
