import { Food } from "./app/shared/models/Food";
import { Tag } from "./app/shared/models/Tag";

export const sample: Food[] = [
  {
    id:'1',
    name:'Pierogi',
    price:12,
    tags:['dinner','cheap','vegetarian'],
    favourite:false,
    stars:4,
    imageUrl:'assets/1.jpeg',
    origins:"Poland",
    cookTime:"25",
    inStock: 15,
  },
  {
    id:'2',
    name:'Pizza',
    price:34,
    tags:['dinner','fast-food','vegetarian'],
    favourite:false,
    stars:3,
    imageUrl:'assets/2.jpg',
    origins:"Italy",
    cookTime:"25",
    inStock: 5,
  },
  {
    id:'3',
    name:'Beetrot soup',
    price:24,
    tags:['soup','spicy'],
    favourite:false,
    stars:5,
    imageUrl:'assets/3.jpg',
    origins:"Poland",
    cookTime:"15",
    inStock: 18,
  },
  {
    id:'4',
    name:'Burger',
    price:35,
    tags:['dinner','fast-food'],
    favourite:true,
    stars:4,
    imageUrl:'assets/4.jpg',
    origins:"International",
    cookTime:"45",
    inStock: 7,
  },
  {
    id:'5',
    name:'Chicken Tikka Masala',
    price:32,
    tags:['dinner','lunch'],
    favourite:false,
    stars:2,
    imageUrl:'assets/5.jpg',
    origins:"India",
    cookTime:"25",
    inStock: 15,
  },
  {
    id:'6',
    name:'Sushi',
    price:52,
    tags:['dinner','supper','fish'],
    favourite:true,
    stars:5,
    imageUrl:'assets/6.jpg',
    origins:"Japan",
    cookTime:"35",
    inStock: 11,
  },
  {
    id:'7',
    name:'Burrito',
    price:35,
    tags:['dinner','spicy'],
    favourite:false,
    stars:4,
    imageUrl:'assets/7.jpg',
    origins:"Mexico",
    cookTime:"20",
    inStock: 30,
  },
  {
    id:'8',
    name:'Salomon sandwitch',
    price:18,
    tags:['breakfast','lunch','fish'],
    favourite:true,
    stars:5,
    imageUrl:'assets/8.jpg',
    origins:"International",
    cookTime:"15",
    inStock: 8,
  },
  {
    id:'9',
    name:'Tofu Stir Fry',
    price:15,
    tags:['cheap','vegan','spicy'],
    favourite:false,
    stars:3,
    imageUrl:'assets/9.jpg',
    origins:"Thai",
    cookTime:"25",
    inStock: 15,
  },
  {
    id:'10',
    name:'Fish and chips',
    price:25,
    tags:['dinner','fish'],
    favourite:false,
    stars:5,
    imageUrl:'assets/10.jpeg',
    origins:"England",
    cookTime:"35",
    inStock: 15,
  },
  {
    id:'11',
    name:'Chili con carne',
    price:25,
    tags:['dinner','spicy','vegetarian'],
    favourite:true,
    stars:5,
    imageUrl:'assets/11.jpeg',
    origins:"Mexico",
    cookTime:"35",
    inStock: 12,
  },
  {
    id:'12',
    name:'Chicken korma',
    price:22,
    tags:['dinner'],
    favourite:false,
    stars:5,
    imageUrl:'assets/12.jpg',
    origins:"India",
    cookTime:"35",
    inStock: 15,
  },
]

export const sample_tags:Tag[] = [
  {name:'dinner', count:9},
  {name:'cheap', count:2},
  {name:'vegetarian',count:3},
  {name:'fast-food',count:2},
  {name:'soup',count:1},
  {name:'spicy',count:4},
  {name:'lunch',count:2},
  {name:'supper',count:1},
  {name:'fish',count:3},
  {name:'breakfast',count:1},
  {name:'vegan',count:1},
]
